# Makefile
# authors: Lincoln Harris
# date: 2.11.18

run_egfr_L858R:
	ipython checkCoverage_parallel.py 7 55191820 55191822 16 cellsList.csv egfr_L858R_coverageByCell.csv 

run_egfr_T790M:
	ipython checkCoverage_parallel.py 7 55181377 55181379 16 cellsList.csv egfr_T790M_coverageByCell.csv 

run_egfr_L861Q:
	ipython checkCoverage_parallel.py 7 55191830 55191832 16 cellsList.csv egfr_L861Q_coverageByCell.csv 

run_egfr_G719X:
	ipython checkCoverage_parallel.py 7 55174014 55174016 16 cellsList.csv egfr_G719X_coverageByCell.csv 

run_egfr_S768I:
	ipython checkCoverage_parallel.py 7 55181311 55181313 16 cellsList.csv egfr_S768I_coverageByCell.csv 

run_braf_V600E:
	ipython checkCoverage_parallel.py 7 140753335 140753337 16 cellsList.csv braf_V600E_coverageByCell.csv

run_kras_G12C:
	ipython checkCoverage_parallel.py 12 25245350 25245352 16 cellsList.csv kras_G12C_coverageByCell.csv

run_kras_G13X:
	ipython checkCoverage_parallel.py 12 25245346 25245348 16 cellsList.csv kras_G13X_coverageByCell.csv

run_kras_Q61X:
	ipython checkCoverage_parallel.py 12 25227340 25227342 16 cellsList.csv kras_Q61X_coverageByCell.csv

run_egfr_exon20ins:
	ipython checkCoverage_parallel.py 7 55181330 55181331 16 cellsList.csv egfr_exon20ins_coverageByCell.csv

run_egfr_exon19del:
	ipython checkCoverage_parallel.py 7 55174772 55174789 16 cellsList.csv egfr_exon19del_coverageByCell.csv




